-- Olive rollout — the 7 migrations, concatenated in timestamp order.
--
-- Generated from supabase/migrations by docs/rollout/README.md's procedure.
-- Every file is re-runnable (IF NOT EXISTS / DROP POLICY IF EXISTS / ON CONFLICT),
-- so running this twice is safe. Do NOT use 'supabase db push' — see the README.
--
-- Prefer running each block separately and reading the output before the next.
-- The whole file is wrapped in a transaction so a mid-way failure rolls back
-- rather than leaving the schema half-applied.

BEGIN;

-- ============================================================================
-- 20260227000000_add_geometry_to_areas.sql
-- ============================================================================
-- Add geometry (GeoJSON Polygon) support to areas and sub-areas.
--
-- Stored as jsonb holding a bare GeoJSON geometry object, e.g.
--   {"type":"Polygon","coordinates":[[[35.2130,31.7690], ... ,[35.2130,31.7690]]]}
--
-- Outdoor areas use WGS84 [lng, lat] pairs and are rendered by
-- components/map/LeafletMap.tsx via L.geoJSON(). Indoor areas reuse the same
-- shape but the numbers are metres in a local L.CRS.Simple canvas space
-- (components/indoor-designer/canvas/IndoorCanvas.tsx).
--
-- Deliberately NOT PostGIS: the extension is not installed and the app reads
-- and writes plain GeoJSON via supabase-js.

ALTER TABLE public.areas     ADD COLUMN IF NOT EXISTS geometry jsonb;
ALTER TABLE public.sub_areas ADD COLUMN IF NOT EXISTS geometry jsonb;

COMMENT ON COLUMN public.areas.geometry IS
  'GeoJSON Polygon. Outdoor: WGS84 [lng, lat], closed ring. Indoor: metres in local canvas space.';
COMMENT ON COLUMN public.sub_areas.geometry IS
  'GeoJSON Polygon nested within the parent area geometry. Same coordinate rules as areas.geometry.';

-- ============================================================================
-- 20260907000000_fix_areas_report_areas_rls_recursion.sql
-- ============================================================================
-- Fix infinite recursion between the areas and report_areas RLS policies.
--
-- The cycle:
--   areas."Users can view areas through report areas"
--       USING (EXISTS (SELECT 1 FROM report_areas ra WHERE ra.area_id = areas.id))
--   report_areas."Users can view accessible report areas"
--       USING (EXISTS (SELECT 1 FROM areas a JOIN customer_areas ... WHERE a.id = report_areas.area_id ...))
--
-- Evaluating either policy triggers the other, so any authenticated SELECT that
-- touches report_areas fails with:
--   42P17: infinite recursion detected in policy for relation "report_areas"
--
-- This broke /api/map/areas, /api/map/monitoring-counts and /api/customer-areas
-- for every non-admin path.
--
-- The areas policy is dropped rather than the report_areas one because it is
-- both the redundant side and an unintended tenancy leak: it granted SELECT on
-- ANY area having ANY report_areas row to ANY authenticated user, ignoring
-- customer ownership entirely. Legitimate access is already covered by
-- "Users can view accessible areas" (customer owners and their workers, via
-- customer_areas) and "Admins can view all areas".

DROP POLICY IF EXISTS "Users can view areas through report areas" ON public.areas;

-- ============================================================================
-- 20260908000000_add_report_number_to_report_areas.sql
-- ============================================================================
-- Add the missing report_areas.report_number column.
--
-- Same class of bug as the empty 20260227000000_add_geometry_to_areas.sql
-- migration: the column exists only on the remote project and was never
-- captured in a migration, so on any fresh database every query selecting it
-- fails with:
--   42703: column report_areas_1.report_number does not exist
--
-- That broke GET /api/reports, GET /api/action-tasks and the reports Excel
-- export ("Unknown error" on the /reports and /actions pages).
--
-- Shape is dictated by types/database.ts (types/database.ts:446,460,474):
-- `report_number: number` on Row (never null) but optional on Insert/Update,
-- i.e. the database assigns it. It is the human-facing report number rendered
-- as "דוח מס׳ N" in components/reports/ReportDetailSheet.tsx and sorted on in
-- components/reports/ReportsTable.tsx, so it must be a stable ascending integer.

ALTER TABLE public.report_areas
  ADD COLUMN IF NOT EXISTS report_number integer GENERATED BY DEFAULT AS IDENTITY;

CREATE INDEX IF NOT EXISTS idx_report_areas_report_number
  ON public.report_areas (report_number);

COMMENT ON COLUMN public.report_areas.report_number IS
  'Human-facing sequential report number, assigned by the database. Displayed as "דוח מס׳ N".';

-- ============================================================================
-- 20260908100000_create_olive_parameters.sql
-- ============================================================================
-- Generic measurement parameters and their threshold rules.
--
-- These two tables move decision thresholds out of application code and into
-- data. The engine knows a measurement has a value, that ranges map to a
-- status, and that a status carries a severity and a Hebrew message. It does
-- not know what "oil" means. Adding a crop later means adding rows, not code.
--
-- Boundary encoding matters and is easy to get wrong. The olive prototype's
-- nirStatus() uses `<` for the lower band but `<=` for the upper:
--   oil 17.0 is "תוכנן למסיק", not "לא מוכן"
--   oil 20.0 is "תוכנן למסיק", not "מסיק מיידי"
-- A plain min/max pair cannot express that, so each rule carries an
-- upper_bound plus an upper_inclusive flag, and rules are evaluated in
-- sort_order with first match winning. A NULL upper_bound is the catch-all
-- and must be the last rule for its parameter.
--
-- Parameters with no rules (green, acid, maturity, irrig) are informational
-- only — spec §4.2 is explicit that colour and acidity have no threshold
-- because too many variables affect them for a defensible cutoff.

CREATE TABLE IF NOT EXISTS parameters (
  code TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  unit TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE parameters IS 'Measurable quantities (oil %, water %, ...). Crop-agnostic.';

CREATE TABLE IF NOT EXISTS parameter_rules (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  parameter_code TEXT NOT NULL REFERENCES parameters(code) ON DELETE CASCADE,
  upper_bound NUMERIC,
  upper_inclusive BOOLEAN NOT NULL DEFAULT TRUE,
  status TEXT NOT NULL CHECK (status IN ('idle', 'ok', 'plan', 'urgent')),
  severity INTEGER NOT NULL DEFAULT 0 CHECK (severity BETWEEN 0 AND 3),
  message TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON COLUMN parameter_rules.upper_bound IS
  'Upper limit of this band. NULL means unbounded — must be the last rule for the parameter.';
COMMENT ON COLUMN parameter_rules.upper_inclusive IS
  'TRUE evaluates value <= upper_bound, FALSE evaluates value < upper_bound.';

CREATE INDEX IF NOT EXISTS idx_parameter_rules_parameter_code
  ON parameter_rules(parameter_code);

CREATE UNIQUE INDEX IF NOT EXISTS idx_parameter_rules_order
  ON parameter_rules(parameter_code, sort_order);

-- -----------------------------------------------------------------------------
-- Seed: olive parameters
-- -----------------------------------------------------------------------------
-- parameters.code is the primary key, so ON CONFLICT (code) is safe here.
-- (Unlike findings/crops/materials, which have no unique constraint on name.)

INSERT INTO parameters (code, label, unit, sort_order) VALUES
  ('oil',      'אחוז שמן',             '%',            1),
  ('water',    'אחוז מים',             '%',            2),
  ('dry',      'אחוז שמן בחומר יבש',   '%',            3),
  ('green',    'אחוז צבע ירוק',        '%',            4),
  ('acid',     'חומציות',              '%',            5),
  ('maturity', 'אינדקס הבשלה',         NULL,           6),
  ('irrig',    'השקיה בפועל',          'קוב/דונם/יום', 7)
ON CONFLICT (code) DO NOTHING;

-- -----------------------------------------------------------------------------
-- Seed: threshold rules, ported verbatim from the prototype's nirStatus()
-- -----------------------------------------------------------------------------

INSERT INTO parameter_rules (parameter_code, upper_bound, upper_inclusive, status, severity, message, sort_order) VALUES
  -- oil:   < 17 idle | 17..20 plan | > 20 urgent
  ('oil',    17,   FALSE, 'idle',   0, 'לא מוכן למסיק',      1),
  ('oil',    20,   TRUE,  'plan',   2, 'תוכנן למסיק',        2),
  ('oil',    NULL, TRUE,  'urgent', 3, 'מסיק מיידי',          3),

  -- water: < 50 urgent | 50..54 ok | 54..60 plan | > 60 urgent
  ('water',  50,   FALSE, 'urgent', 3, 'עקת מים',            1),
  ('water',  54,   TRUE,  'ok',     1, 'אופטימום',           2),
  ('water',  60,   TRUE,  'plan',   2, 'צמצום השקיה',        3),
  ('water',  NULL, TRUE,  'urgent', 3, 'סגירת מים מיידית',   4),

  -- dry:   < 40 idle | 40..45 plan | > 45 urgent
  ('dry',    40,   FALSE, 'idle',   0, '—',                   1),
  ('dry',    45,   TRUE,  'plan',   2, 'תשומת לב / החלטה',   2),
  ('dry',    NULL, TRUE,  'urgent', 3, 'מסיק',                3)
ON CONFLICT (parameter_code, sort_order) DO NOTHING;

-- -----------------------------------------------------------------------------
-- RLS
-- -----------------------------------------------------------------------------
-- Global configuration, not customer-scoped: every authenticated user reads,
-- admins and customer owners manage. Mirrors the findings/crops policies added
-- in 20260321100000_allow_customer_owner_manage_sync_tables.sql.

ALTER TABLE parameters ENABLE ROW LEVEL SECURITY;
ALTER TABLE parameter_rules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read parameters" ON parameters;
CREATE POLICY "Anyone can read parameters"
  ON parameters FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Allow admin or owner manage parameters" ON parameters;
CREATE POLICY "Allow admin or owner manage parameters"
  ON parameters FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid() AND r.name IN ('admin', 'customer_owner')
    )
  );

DROP POLICY IF EXISTS "Anyone can read parameter_rules" ON parameter_rules;
CREATE POLICY "Anyone can read parameter_rules"
  ON parameter_rules FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Allow admin or owner manage parameter_rules" ON parameter_rules;
CREATE POLICY "Allow admin or owner manage parameter_rules"
  ON parameter_rules FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid() AND r.name IN ('admin', 'customer_owner')
    )
  );

-- ============================================================================
-- 20260908110000_create_olive_plot_tables.sql
-- ============================================================================
-- Olive-harvest domain tables that hang off the existing areas tree.
--
-- An olive plot (חלקה) IS an `areas` row — that table already carries name,
-- variety, planting_time, size, crop_id and geometry, so only the nine
-- olive-specific fields need a home. olive_plot_details is 1:1 with areas and
-- holds exactly those. Takts (טאקטים) are `sub_areas` rows. Multi-tenancy
-- arrives for free through customer_areas.
--
-- Lookup values are stored as English codes and displayed in Hebrew from
-- types/database.ts, matching how worker_types already works.
--
-- RLS NOTE — a deliberate deviation from observed practice.
-- Every shipped policy in this repo inlines a multi-table EXISTS chain, while
-- can_access_area() from 20260208000000_consolidate_rls_helpers.sql has sat
-- unused since it was added. These tables adopt it, for three reasons:
--   1. It is SECURITY DEFINER, so it does not re-enter RLS and is structurally
--      immune to the 42P17 recursion that broke /api/map/areas in
--      20260907000000. That bug came from a policy reaching *down* into a
--      child table; a SECURITY DEFINER helper cannot close such a loop.
--   2. 20260208000000's own trailing comment documents this exact usage.
--   3. One line instead of twelve, so the tenancy rule is auditable at a glance.
-- The invariant still holds either way: authorization flows one direction only,
-- child -> customer_areas -> customers. No policy here reaches into a child.

-- -----------------------------------------------------------------------------
-- 1. Plot details (1:1 with areas)
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS olive_plot_details (
  area_id UUID PRIMARY KEY REFERENCES areas(id) ON DELETE CASCADE,
  grower_name TEXT,
  region TEXT,
  plot_type TEXT CHECK (plot_type IS NULL OR plot_type IN ('owner', 'partner', 'occasional')),
  harvester TEXT CHECK (harvester IS NULL OR harvester IN ('1190x', '9090x', 'other')),
  water_type TEXT CHECK (water_type IS NULL OR water_type IN ('fresh', 'reclaimed', 'kinneret')),
  takt_count INTEGER CHECK (takt_count IS NULL OR takt_count BETWEEN 1 AND 10),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE olive_plot_details IS
  'Olive-specific attributes for an area. The plot itself lives in areas.';
COMMENT ON COLUMN olive_plot_details.region IS
  'גוש — a grouping label, deliberately a field rather than a parent area (see design §4.2).';

-- -----------------------------------------------------------------------------
-- 2. Seasons (מחזור מסיק)
-- -----------------------------------------------------------------------------
-- Replaces the prototype's two loose globals, harvestYear and harvestYearType.
-- year_type is the olive's natural alternate-bearing cycle: ON is a heavy year,
-- OFF a light one.

CREATE TABLE IF NOT EXISTS seasons (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  year_type TEXT CHECK (year_type IS NULL OR year_type IN ('ON', 'OFF')),
  starts_on DATE NOT NULL,
  ends_on DATE NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT seasons_dates_ordered CHECK (ends_on >= starts_on)
);

CREATE INDEX IF NOT EXISTS idx_seasons_active ON seasons(is_active) WHERE is_active;

-- -----------------------------------------------------------------------------
-- 3. Yield estimates (area x season)
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS yield_estimates (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  area_id UUID NOT NULL REFERENCES areas(id) ON DELETE CASCADE,
  season_id UUID NOT NULL REFERENCES seasons(id) ON DELETE CASCADE,
  kg_per_dunam NUMERIC(10, 2),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT yield_estimates_area_season_unique UNIQUE (area_id, season_id)
);

CREATE INDEX IF NOT EXISTS idx_yield_estimates_area_id ON yield_estimates(area_id);
CREATE INDEX IF NOT EXISTS idx_yield_estimates_season_id ON yield_estimates(season_id);

-- -----------------------------------------------------------------------------
-- 4. Variety harvest windows (חלונות קטיף)
-- -----------------------------------------------------------------------------
-- Accumulated agronomic knowledge: when each variety is normally picked.
-- Dates are day/month only because the window recurs every year. Stored as
-- text in DD/MM form, exactly as the prototype does, so a window may wrap the
-- turn of the year.

CREATE TABLE IF NOT EXISTS variety_windows (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  variety TEXT NOT NULL,
  start_dm TEXT NOT NULL CHECK (start_dm ~ '^\d{1,2}/\d{1,2}$'),
  end_dm TEXT NOT NULL CHECK (end_dm ~ '^\d{1,2}/\d{1,2}$'),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_variety_windows_variety ON variety_windows(variety);

-- -----------------------------------------------------------------------------
-- 5. Weather days
-- -----------------------------------------------------------------------------
-- Two rows may exist per date: the fetched forecast (is_manual = false) and a
-- manual override (is_manual = true). The manual row wins in application logic,
-- which is why the unique constraint spans both columns rather than date alone.

CREATE TABLE IF NOT EXISTS weather_days (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  entry_date DATE NOT NULL,
  temp_min NUMERIC(5, 2),
  temp_max NUMERIC(5, 2),
  rain_mm NUMERIC(6, 2),
  wind_kmh NUMERIC(6, 2),
  is_manual BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT weather_days_date_source_unique UNIQUE (entry_date, is_manual)
);

CREATE INDEX IF NOT EXISTS idx_weather_days_entry_date ON weather_days(entry_date);

-- -----------------------------------------------------------------------------
-- RLS
-- -----------------------------------------------------------------------------

ALTER TABLE olive_plot_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE seasons ENABLE ROW LEVEL SECURITY;
ALTER TABLE yield_estimates ENABLE ROW LEVEL SECURITY;
ALTER TABLE variety_windows ENABLE ROW LEVEL SECURITY;
ALTER TABLE weather_days ENABLE ROW LEVEL SECURITY;

-- Area-scoped. can_access_area already folds in the admin bypass, so no
-- separate is_admin_user clause is needed. FOR ALL with only USING means
-- Postgres reuses USING as the INSERT/UPDATE check, matching house style.
DROP POLICY IF EXISTS "Users can manage olive plot details for their areas" ON olive_plot_details;
CREATE POLICY "Users can manage olive plot details for their areas"
  ON olive_plot_details FOR ALL
  USING (can_access_area(area_id, auth.uid()));

DROP POLICY IF EXISTS "Users can manage yield estimates for their areas" ON yield_estimates;
CREATE POLICY "Users can manage yield estimates for their areas"
  ON yield_estimates FOR ALL
  USING (can_access_area(area_id, auth.uid()));

-- Shared reference data: everyone reads, admins and customer owners manage.
DROP POLICY IF EXISTS "Anyone can read seasons" ON seasons;
CREATE POLICY "Anyone can read seasons"
  ON seasons FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Allow admin or owner manage seasons" ON seasons;
CREATE POLICY "Allow admin or owner manage seasons"
  ON seasons FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid() AND r.name IN ('admin', 'customer_owner')
    )
  );

DROP POLICY IF EXISTS "Anyone can read variety_windows" ON variety_windows;
CREATE POLICY "Anyone can read variety_windows"
  ON variety_windows FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Allow admin or owner manage variety_windows" ON variety_windows;
CREATE POLICY "Allow admin or owner manage variety_windows"
  ON variety_windows FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid() AND r.name IN ('admin', 'customer_owner')
    )
  );

-- Weather is regional, not per-customer, and the manual-override form is used
-- by ops staff in the field, so any authenticated worker may write it.
DROP POLICY IF EXISTS "Anyone can read weather_days" ON weather_days;
CREATE POLICY "Anyone can read weather_days"
  ON weather_days FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Authenticated users can manage weather_days" ON weather_days;
CREATE POLICY "Authenticated users can manage weather_days"
  ON weather_days FOR ALL
  TO authenticated
  USING (true);

-- ============================================================================
-- 20260908120000_create_olive_report_types.sql
-- ============================================================================
-- NIR measurements and harvest passes as report types.
--
-- report_areas is already a report header with a pluggable type: report_area_types
-- is a lookup, and monitoring_area_report / actions_area_report are its per-type
-- detail tables. Olive adds two more types on the same pattern, which is why
-- neither needs its own header table, numbering, or worker attribution.
--
--   nir     — one ripeness measurement (בדיקת NIR)
--   harvest — one harvest pass (מסיק), several per plot per season
--
-- Both detail tables are keyed 1:1 on report_areas.id, unlike the monitoring and
-- action detail tables which hold many rows per report (one per finding). A NIR
-- measurement and a harvest pass are each a single event with a single set of
-- values, so 1:1 is correct here.
--
-- KNOWN CONSEQUENCE, deliberately accepted: report_areas.report_number is a
-- single global identity across all report types (added in 20260908000000), so
-- NIR rows consume numbers from the same sequence as pest monitoring reports and
-- appear in the /reports list. The reports list therefore needs a type filter.
-- If that inflation proves unacceptable in use, NIR is the type to split back
-- out into a standalone time-series table; harvest should stay a report either
-- way, since it is genuinely an event with a date and a responsible worker.

INSERT INTO report_area_types (name, display_name, description) VALUES
  ('nir',     'בדיקת NIR', 'NIR ripeness measurement'),
  ('harvest', 'מסיק',      'Olive harvest pass')
ON CONFLICT (name) DO NOTHING;

-- -----------------------------------------------------------------------------
-- NIR detail
-- -----------------------------------------------------------------------------
-- `dry` (שמן בחומר יבש) is derived, never entered: oil / (100 - water) * 100.
-- Storing it generated keeps the prototype's formula in one place and makes it
-- queryable. The water < 100 guard avoids a division by zero on bad input.

CREATE TABLE IF NOT EXISTS nir_report (
  report_area_id UUID PRIMARY KEY REFERENCES report_areas(id) ON DELETE CASCADE,
  sub_area_id UUID REFERENCES sub_areas(id) ON DELETE SET NULL,
  oil NUMERIC(5, 2) CHECK (oil IS NULL OR oil BETWEEN 0 AND 100),
  water NUMERIC(5, 2) CHECK (water IS NULL OR water BETWEEN 0 AND 100),
  dry NUMERIC(6, 2) GENERATED ALWAYS AS (
    CASE
      WHEN oil IS NOT NULL AND water IS NOT NULL AND water < 100
      THEN round(oil / (100 - water) * 100, 2)
    END
  ) STORED,
  green NUMERIC(5, 2) CHECK (green IS NULL OR green BETWEEN 0 AND 100),
  acid NUMERIC(5, 2),
  maturity NUMERIC(5, 2),
  irrig_amount NUMERIC(10, 2),
  direction TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON COLUMN nir_report.sub_area_id IS 'The takt sampled, when the sample is not plot-wide.';
COMMENT ON COLUMN nir_report.dry IS 'Derived: oil / (100 - water) * 100. Never entered by hand.';
COMMENT ON COLUMN nir_report.green IS 'Informational only — spec §4.2 defines no threshold for colour.';

CREATE INDEX IF NOT EXISTS idx_nir_report_sub_area_id ON nir_report(sub_area_id);

-- -----------------------------------------------------------------------------
-- Harvest detail
-- -----------------------------------------------------------------------------
-- One row per pass. is_final marks the pass that completes the plot, which is
-- what moves it out of the active list — replacing the prototype's single
-- boolean harvestStatus flag.

CREATE TABLE IF NOT EXISTS harvest_report (
  report_area_id UUID PRIMARY KEY REFERENCES report_areas(id) ON DELETE CASCADE,
  sub_area_id UUID REFERENCES sub_areas(id) ON DELETE SET NULL,
  pass_number INTEGER NOT NULL DEFAULT 1 CHECK (pass_number > 0),
  harvester_type TEXT,
  operator TEXT,
  area_done_dunam NUMERIC(10, 2),
  fruit_kg NUMERIC(12, 2),
  oil_kg NUMERIC(12, 2),
  is_final BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON COLUMN harvest_report.is_final IS 'Marks the pass that completes the plot for this season.';

CREATE INDEX IF NOT EXISTS idx_harvest_report_sub_area_id ON harvest_report(sub_area_id);

-- -----------------------------------------------------------------------------
-- RLS
-- -----------------------------------------------------------------------------
-- Both tables reach tenancy through their parent report_areas row.
-- can_access_report_area is SECURITY DEFINER and already folds in the admin
-- bypass. It reaches upward only (detail -> report_areas -> areas ->
-- customer_areas -> customers), so it cannot recreate the 42P17 cycle fixed in
-- 20260907000000.

ALTER TABLE nir_report ENABLE ROW LEVEL SECURITY;
ALTER TABLE harvest_report ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can manage nir reports for their areas" ON nir_report;
CREATE POLICY "Users can manage nir reports for their areas"
  ON nir_report FOR ALL
  USING (can_access_report_area(report_area_id, auth.uid()));

DROP POLICY IF EXISTS "Users can manage harvest reports for their areas" ON harvest_report;
CREATE POLICY "Users can manage harvest reports for their areas"
  ON harvest_report FOR ALL
  USING (can_access_report_area(report_area_id, auth.uid()));

-- ============================================================================
-- 20260908140000_add_plant_year_label.sql
-- ============================================================================
-- Free-text planting year for olive plots.
--
-- areas.planting_time is a DATE (added in 20260308100000). The olive spec §5.1
-- is explicit that the planting year is free text in practice, because the
-- client's real data contains values a date cannot hold:
--
--   '2006/7'   a block planted across two seasons
--   '2003'     a year with no month or day
--
-- Casting those to a DATE either fails or invents precision that was never
-- recorded — '2006/7' would silently become 2006-01-01 and the fact that it
-- spans two seasons would be lost.
--
-- So the DATE column stays authoritative for anything doing date arithmetic,
-- and this column carries the label the grower actually uses. The UI prefers
-- the label when present and falls back to planting_time.

ALTER TABLE olive_plot_details
  ADD COLUMN IF NOT EXISTS plant_year_label TEXT;

COMMENT ON COLUMN olive_plot_details.plant_year_label IS
  'Planting year as the grower writes it, e.g. "2006/7". Falls back to areas.planting_time when null.';

COMMIT;
