-- Olive rollout — CONVERT report_areas.report_number TO AN IDENTITY COLUMN.
--
-- WHY THIS FILE EXISTS
-- Production already has report_areas.report_number as a PLAIN INTEGER
-- (is_identity=NO). Migration 20260908000000 says:
--
--   ALTER TABLE public.report_areas
--     ADD COLUMN IF NOT EXISTS report_number integer GENERATED BY DEFAULT AS IDENTITY;
--
-- Because the column exists, IF NOT EXISTS suppresses the whole statement —
-- including the identity property. The migration would report success and
-- change nothing, leaving every future INSERT with a NULL report_number.
--
-- Run this INSTEAD of relying on that migration, and run it BEFORE
-- 01-migrations-in-order.sql. That bundle then no-ops this column correctly.
--
-- Safe to re-run: the DO block exits early if the column is already an identity.
-- One transaction: a failure anywhere leaves the column exactly as it was.
--
-- RUN IT STANDALONE. It contains its own BEGIN/COMMIT, so pasting it inside
-- another transaction will COMMIT that outer transaction too. (Learned the hard
-- way: a test harness that wrapped this in BEGIN ... ROLLBACK had its ROLLBACK
-- turn into "no transaction in progress" and the changes persisted.)
--
-- Verified against a local database put into production's exact shape — plain
-- integer column, NULLs present: 3 NULLs were numbered from max+1, the column
-- became identity/NOT NULL with no default, a fresh INSERT received max+1
-- automatically, and no duplicates resulted.

BEGIN;

DO $$
DECLARE
  v_is_identity text;
  v_max         bigint;
  v_nulls       bigint;
  v_dupes       bigint;
BEGIN
  SELECT is_identity INTO v_is_identity
  FROM information_schema.columns
  WHERE table_schema = 'public'
    AND table_name   = 'report_areas'
    AND column_name  = 'report_number';

  IF v_is_identity IS NULL THEN
    RAISE EXCEPTION 'report_areas.report_number does not exist — run migration 20260908000000 instead';
  END IF;

  IF v_is_identity = 'YES' THEN
    RAISE NOTICE 'report_number is already an identity column — nothing to do';
    RETURN;
  END IF;

  -- Refuse to proceed on duplicates. A report number is shown to users as
  -- "דוח מס׳ N"; two reports sharing one is worse than none having one, and
  -- silently renumbering somebody's existing reports is not this script's call.
  SELECT count(*) INTO v_dupes FROM (
    SELECT report_number FROM public.report_areas
    WHERE report_number IS NOT NULL
    GROUP BY report_number HAVING count(*) > 1
  ) d;
  IF v_dupes > 0 THEN
    RAISE EXCEPTION 'report_number has % duplicated value(s) — resolve them first', v_dupes;
  END IF;

  -- 1. Backfill NULLs, oldest report first, continuing above the current max.
  SELECT count(*) FILTER (WHERE report_number IS NULL),
         coalesce(max(report_number), 0)
    INTO v_nulls, v_max
    FROM public.report_areas;

  IF v_nulls > 0 THEN
    RAISE NOTICE 'numbering % report(s) with no report_number, starting at %', v_nulls, v_max + 1;
    UPDATE public.report_areas r
       SET report_number = v_max + n.rn
      FROM (
        SELECT id, row_number() OVER (ORDER BY created_at, id) AS rn
        FROM public.report_areas
        WHERE report_number IS NULL
      ) n
     WHERE r.id = n.id;
  END IF;

  -- 2. A leftover default would conflict with ADD GENERATED.
  EXECUTE 'ALTER TABLE public.report_areas ALTER COLUMN report_number DROP DEFAULT';

  -- 3. ADD GENERATED requires NOT NULL.
  EXECUTE 'ALTER TABLE public.report_areas ALTER COLUMN report_number SET NOT NULL';

  -- 4. Attach the identity.
  EXECUTE 'ALTER TABLE public.report_areas ALTER COLUMN report_number ADD GENERATED BY DEFAULT AS IDENTITY';

  -- 5. Start the sequence past everything that already exists, or the next
  --    insert collides with a hand-written number.
  SELECT coalesce(max(report_number), 0) INTO v_max FROM public.report_areas;
  PERFORM setval(pg_get_serial_sequence('public.report_areas', 'report_number'), v_max + 1, false);

  RAISE NOTICE 'report_number is now an identity column; next value is %', v_max + 1;
END $$;

-- The index migration 20260908000000 also creates. Harmless to run twice.
CREATE INDEX IF NOT EXISTS idx_report_areas_report_number
  ON public.report_areas (report_number);

COMMIT;


-- Verify (run separately, after COMMIT):
--
-- select column_name, is_identity, identity_generation, is_nullable, column_default
-- from information_schema.columns
-- where table_schema='public' and table_name='report_areas' and column_name='report_number';
--   -> want is_identity=YES, identity_generation=BY DEFAULT, is_nullable=NO
--
-- select count(*), count(report_number), min(report_number), max(report_number)
-- from report_areas;
--   -> want count = count(report_number), i.e. no NULLs left
