-- =============================================================================
-- Olive harvest module — demo seed
-- =============================================================================
--
-- Creates enough data to exercise every path in the olive module: all four
-- status cards populated, weather escalation, a harvested plot, and the
-- preserved computePlotStatus / classifyPlotCategory divergence.
--
-- Run against LOCAL Docker Supabase only:
--   docker exec -i supabase_db_area-control-loop \
--     psql -U postgres -d postgres -v confirm=yes \
--     -f - < supabase/seed/olive_demo_seed.sql
--
-- Re-runnable: every id is a pinned literal and the script deletes its own
-- rows first. It touches nothing outside the ids it owns, so the
-- pest-management demo data from reset_and_seed_full.sql is unaffected.
--
-- Id namespaces (extending the scheme in reset_and_seed_full.sql):
--   a8ff… areas (olive)     a9ff… sub_areas (takts)
--   b1ff… report_areas      c1ff… seasons
--
-- Note on report_number: it is GENERATED BY DEFAULT AS IDENTITY and shared
-- across ALL report types, so these rows consume numbers from the same
-- sequence as the pest-management demo reports. That is expected.
-- =============================================================================

\if :{?confirm}
\else
\echo ''
\echo 'REFUSING TO RUN: re-run with -v confirm=yes if this is your local Docker database.'
\echo ''
\quit
\endif

\set ON_ERROR_STOP on
\timing off

BEGIN;

-- -----------------------------------------------------------------------------
-- Reset just this script's rows
-- -----------------------------------------------------------------------------
DELETE FROM public.report_areas WHERE id::text LIKE 'b1ff%';
DELETE FROM public.seasons      WHERE id::text LIKE 'c1ff%';
DELETE FROM public.sub_areas    WHERE id::text LIKE 'a9ff%';
DELETE FROM public.customer_areas WHERE area_id::text LIKE 'a8ff%';
DELETE FROM public.areas        WHERE id::text LIKE 'a8ff%';
DELETE FROM public.variety_windows WHERE variety IN ('ארבקינה', 'קורנייקי', 'ברנע');
DELETE FROM public.weather_days WHERE entry_date >= CURRENT_DATE - 1;

-- -----------------------------------------------------------------------------
-- Plots — six olive areas, all crop = זית so the nav feature gate switches on
-- -----------------------------------------------------------------------------
-- planting_time is a DATE, so it gets 1 January of the planting year. The
-- label the grower actually uses — including '2006/7', which no date can
-- express — lives in olive_plot_details.plant_year_label below.
INSERT INTO public.areas (id, name, description, crop_id, size, size_unit_type, area_type, variety, planting_time)
SELECT v.id, v.name, 'חלקת זית — נתוני הדגמה', c.id, v.size, 'dunam', 'outdoor', v.variety, v.plant_date
FROM (VALUES
  ('a8ff0000-0000-4000-8000-000000000001'::uuid, 'מיצר אגוזי — 2003 — ארבקינה',  18.2, 'ארבקינה',  DATE '2003-01-01'),
  ('a8ff0000-0000-4000-8000-000000000002'::uuid, 'מיצר אגוזי — 2006/7 — קורנייקי', 54.6, 'קורנייקי', DATE '2006-01-01'),
  ('a8ff0000-0000-4000-8000-000000000003'::uuid, 'בית זרע — 2014 — ארבקינה',      12.5, 'ארבקינה',  DATE '2014-01-01'),
  ('a8ff0000-0000-4000-8000-000000000004'::uuid, 'כנות — 2018 — ברנע',            35.7, 'ברנע',     DATE '2018-01-01'),
  ('a8ff0000-0000-4000-8000-000000000005'::uuid, 'שקמים — 2023 — קורנייקי',       60.0, 'קורנייקי', DATE '2023-01-01'),
  ('a8ff0000-0000-4000-8000-000000000006'::uuid, 'פלוגות — 2016 — ארבקינה',        15.6, 'ארבקינה',  DATE '2016-01-01')
) AS v(id, name, size, variety, plant_date)
CROSS JOIN (SELECT id FROM public.crops WHERE name = 'זית' LIMIT 1) c;

-- Every customer can see them, so any demo login works.
INSERT INTO public.customer_areas (customer_id, area_id)
SELECT c.id, a.id FROM public.customers c CROSS JOIN public.areas a
WHERE a.id::text LIKE 'a8ff%'
ON CONFLICT DO NOTHING;

-- Takts. Two plots are subdivided and four are not, which is realistic —
-- takt_count is optional in the spec — and it exercises both the populated
-- dropdown and the "אין טאקטים" empty state on the NIR form.
INSERT INTO public.sub_areas (id, area_id, level, name, variety, size, size_unit_type) VALUES
  ('a9ff0000-0000-4000-8000-000000000001', 'a8ff0000-0000-4000-8000-000000000001', 1, 'טאקט 1', 'ארבקינה', 6.1, 'dunam'),
  ('a9ff0000-0000-4000-8000-000000000002', 'a8ff0000-0000-4000-8000-000000000001', 1, 'טאקט 2', 'ארבקינה', 6.0, 'dunam'),
  ('a9ff0000-0000-4000-8000-000000000003', 'a8ff0000-0000-4000-8000-000000000001', 1, 'טאקט 3', 'ארבקינה', 6.1, 'dunam'),
  ('a9ff0000-0000-4000-8000-000000000004', 'a8ff0000-0000-4000-8000-000000000002', 1, 'טאקט 1', 'קורנייקי', 18.2, 'dunam'),
  ('a9ff0000-0000-4000-8000-000000000005', 'a8ff0000-0000-4000-8000-000000000002', 1, 'טאקט 2', 'קורנייקי', 18.2, 'dunam'),
  ('a9ff0000-0000-4000-8000-000000000006', 'a8ff0000-0000-4000-8000-000000000002', 1, 'טאקט 3', 'קורנייקי', 18.2, 'dunam');

-- -----------------------------------------------------------------------------
-- Olive-specific plot attributes
-- -----------------------------------------------------------------------------
-- plant_year_label carries '2006/7' verbatim — the case that proves why the
-- DATE column alone is not enough.
INSERT INTO public.olive_plot_details (area_id, grower_name, region, plot_type, harvester, water_type, takt_count, plant_year_label) VALUES
  ('a8ff0000-0000-4000-8000-000000000001', 'קיבוץ גשור',    'מיצר אגוזי', 'owner',      '1190x', 'fresh',     3,    '2003'),
  ('a8ff0000-0000-4000-8000-000000000002', 'קיבוץ גשור',    'מיצר אגוזי', 'owner',      '1190x', 'fresh',     3,    '2006/7'),
  ('a8ff0000-0000-4000-8000-000000000003', 'קיבוץ גשור',    'בית זרע',    'owner',      '9090x', 'reclaimed', NULL, '2014'),
  ('a8ff0000-0000-4000-8000-000000000004', 'קיבוץ גשור',    'כנות',       'owner',      '9090x', 'kinneret',  NULL, '2018'),
  ('a8ff0000-0000-4000-8000-000000000005', 'אחוזת נאור',    'שקמים',      'partner',    'other', 'fresh',     NULL, '2023'),
  ('a8ff0000-0000-4000-8000-000000000006', 'מטע פלוגות',    'פלוגות',     'occasional', 'other', 'reclaimed', NULL, '2016')
ON CONFLICT (area_id) DO UPDATE SET
  grower_name = EXCLUDED.grower_name, region = EXCLUDED.region,
  plot_type = EXCLUDED.plot_type, harvester = EXCLUDED.harvester,
  water_type = EXCLUDED.water_type, takt_count = EXCLUDED.takt_count,
  plant_year_label = EXCLUDED.plant_year_label;

-- -----------------------------------------------------------------------------
-- Season + yield estimates spanning the three load bands
-- -----------------------------------------------------------------------------
INSERT INTO public.seasons (id, name, year_type, starts_on, ends_on, is_active) VALUES
  ('c1ff0000-0000-4000-8000-000000000001', 'מסיק 2026', 'ON', '2026-09-01', '2026-12-31', true);

INSERT INTO public.yield_estimates (area_id, season_id, kg_per_dunam) VALUES
  ('a8ff0000-0000-4000-8000-000000000001', 'c1ff0000-0000-4000-8000-000000000001', 1500),  -- גבוה
  ('a8ff0000-0000-4000-8000-000000000002', 'c1ff0000-0000-4000-8000-000000000001', 1200),  -- בינוני
  ('a8ff0000-0000-4000-8000-000000000003', 'c1ff0000-0000-4000-8000-000000000001', 1400),  -- גבוה
  ('a8ff0000-0000-4000-8000-000000000004', 'c1ff0000-0000-4000-8000-000000000001',  750),  -- נמוך
  ('a8ff0000-0000-4000-8000-000000000005', 'c1ff0000-0000-4000-8000-000000000001', 1700),  -- גבוה
  ('a8ff0000-0000-4000-8000-000000000006', 'c1ff0000-0000-4000-8000-000000000001',  350)   -- נמוך
ON CONFLICT (area_id, season_id) DO UPDATE SET kg_per_dunam = EXCLUDED.kg_per_dunam;

-- -----------------------------------------------------------------------------
-- Variety harvest windows — one current, one not
-- -----------------------------------------------------------------------------
INSERT INTO public.variety_windows (variety, start_dm, end_dm) VALUES
  ('ארבקינה',  '15/09', '31/10'),
  ('קורנייקי', '01/10', '30/11'),
  ('ברנע',     '01/02', '28/02');

-- -----------------------------------------------------------------------------
-- Weather — a wet day ahead, which escalates any plot already at "urgent" oil
-- -----------------------------------------------------------------------------
INSERT INTO public.weather_days (entry_date, temp_min, temp_max, rain_mm, wind_kmh, is_manual) VALUES
  (CURRENT_DATE,     16, 29,  0.0,  12, false),
  (CURRENT_DATE + 1, 15, 27, 11.4,  18, false),   -- > 5mm  ⇒ rainSoon
  (CURRENT_DATE + 2, 14, 25,  2.0,  31, false),   -- > 25km/h ⇒ windSoon
  (CURRENT_DATE + 3, 15, 26,  0.0,   9, false);

-- -----------------------------------------------------------------------------
-- NIR measurements, one per plot, chosen to land in different bands
-- -----------------------------------------------------------------------------
INSERT INTO public.report_areas (id, area_id, area_type_id, name, description, status, completion_percentage, report_date) VALUES
  ('b1ff0000-0000-4000-8000-000000000001', 'a8ff0000-0000-4000-8000-000000000001', 'nir', 'בדיקת NIR - מיצר אגוזי 2003', 'בדיקת NIR', 'completed', 100, CURRENT_DATE - 1),
  ('b1ff0000-0000-4000-8000-000000000002', 'a8ff0000-0000-4000-8000-000000000002', 'nir', 'בדיקת NIR - מיצר אגוזי 2006/7', 'בדיקת NIR', 'completed', 100, CURRENT_DATE - 2),
  ('b1ff0000-0000-4000-8000-000000000003', 'a8ff0000-0000-4000-8000-000000000003', 'nir', 'בדיקת NIR - בית זרע 2014', 'בדיקת NIR', 'completed', 100, CURRENT_DATE - 3),
  ('b1ff0000-0000-4000-8000-000000000004', 'a8ff0000-0000-4000-8000-000000000004', 'nir', 'בדיקת NIR - כנות 2018', 'בדיקת NIR', 'completed', 100, CURRENT_DATE - 4),
  ('b1ff0000-0000-4000-8000-000000000006', 'a8ff0000-0000-4000-8000-000000000006', 'nir', 'בדיקת NIR - פלוגות 2016', 'בדיקת NIR', 'completed', 100, CURRENT_DATE - 6);

-- dry is GENERATED and must not be supplied.
INSERT INTO public.nir_report (report_area_id, sub_area_id, oil, water, green, acid, maturity, irrig_amount, direction) VALUES
  -- oil 21 ⇒ urgent. With rain tomorrow the headline becomes "מסיק דחוף".
  ('b1ff0000-0000-4000-8000-000000000001', 'a9ff0000-0000-4000-8000-000000000003', 21.0, 52.0, 28, 0.30, 3.4, 0.00, 'מערב'),
  -- THE DIVERGENCE: oil 19.4 ⇒ plan, but dry computes to 45.33 ⇒ urgent.
  -- Reads "מתוכנן למסיק בקרוב" in the alerts list and "חריגה" on the status card.
  ('b1ff0000-0000-4000-8000-000000000002', NULL, 19.4, 57.2, 35, 0.32, 3.1, 0.25, 'צפון'),
  -- oil 18 / water 52 ⇒ plan + optimum ⇒ תקין
  ('b1ff0000-0000-4000-8000-000000000003', NULL, 18.0, 52.0, 40, 0.28, 2.9, 0.50, 'דרום'),
  -- water 45 ⇒ water stress ⇒ חריגה, while oil is still low
  ('b1ff0000-0000-4000-8000-000000000004', NULL, 12.0, 45.0, 62, 0.21, 1.8, 1.00, 'מזרח'),
  -- oil 22 ⇒ urgent, on the plot that is then harvested below
  ('b1ff0000-0000-4000-8000-000000000006', NULL, 22.1, 50.5, 22, 0.35, 3.8, 0.00, 'מרכז');

-- Plot 5 (שקמים) gets NO measurement, so it lands in "בבדיקות".

-- -----------------------------------------------------------------------------
-- One completed harvest — is_final retires the plot from the active list
-- -----------------------------------------------------------------------------
INSERT INTO public.report_areas (id, area_id, area_type_id, name, description, status, completion_percentage, report_date) VALUES
  ('b1ff0000-0000-4000-8000-000000000010', 'a8ff0000-0000-4000-8000-000000000006', 'harvest', 'מסיק מעבר 1 - פלוגות 2016', 'דוח מסיק', 'completed', 100, CURRENT_DATE - 1);

INSERT INTO public.harvest_report (report_area_id, pass_number, harvester_type, operator, area_done_dunam, fruit_kg, oil_kg, is_final) VALUES
  ('b1ff0000-0000-4000-8000-000000000010', 1, 'other', 'צוות א', 15.6, 5460, 1010, true);

COMMIT;

-- =============================================================================
-- Verification
-- =============================================================================
\echo ''
\echo '--- expected dashboard cards: בבדיקות 1 · תקין 1 · חריגה 2 · מוכן למסיק 1 ---'
SELECT
  a.name,
  n.oil, n.water, n.dry,
  CASE
    WHEN n.oil IS NULL THEN 'בבדיקות'
    WHEN n.oil > 20 THEN 'מוכן למסיק'
    WHEN n.water < 50 OR n.water > 60 OR n.dry > 45 THEN 'חריגה'
    WHEN n.oil >= 17 THEN 'תקין'
    ELSE 'בבדיקות'
  END AS expected_card
FROM public.areas a
LEFT JOIN public.report_areas ra ON ra.area_id = a.id AND ra.area_type_id = 'nir'
LEFT JOIN public.nir_report n ON n.report_area_id = ra.id
WHERE a.id::text LIKE 'a8ff%'
  AND a.id <> 'a8ff0000-0000-4000-8000-000000000006'
ORDER BY a.name;

\echo ''
\echo '--- row counts ---'
SELECT 'areas' t, count(*) FROM public.areas WHERE id::text LIKE 'a8ff%'
UNION ALL SELECT 'plot_details', count(*) FROM public.olive_plot_details
UNION ALL SELECT 'nir_report', count(*) FROM public.nir_report
UNION ALL SELECT 'harvest_report', count(*) FROM public.harvest_report
UNION ALL SELECT 'yield_estimates', count(*) FROM public.yield_estimates
UNION ALL SELECT 'weather_days', count(*) FROM public.weather_days;
