-- Add the missing report_areas.report_number column.
--
-- Same class of bug as the empty 20260227000000_add_geometry_to_areas.sql
-- migration: the column exists only on the remote project and was never
-- captured in a migration, so on any fresh database every query selecting it
-- fails with:
--   42703: column report_areas_1.report_number does not exist
--
-- That broke GET /api/reports, GET /api/action-tasks and the reports Excel
-- export ("Unknown error" on the /reports and /actions pages).
--
-- Shape is dictated by types/database.ts (types/database.ts:446,460,474):
-- `report_number: number` on Row (never null) but optional on Insert/Update,
-- i.e. the database assigns it. It is the human-facing report number rendered
-- as "דוח מס׳ N" in components/reports/ReportDetailSheet.tsx and sorted on in
-- components/reports/ReportsTable.tsx, so it must be a stable ascending integer.

ALTER TABLE public.report_areas
  ADD COLUMN IF NOT EXISTS report_number integer GENERATED BY DEFAULT AS IDENTITY;

CREATE INDEX IF NOT EXISTS idx_report_areas_report_number
  ON public.report_areas (report_number);

COMMENT ON COLUMN public.report_areas.report_number IS
  'Human-facing sequential report number, assigned by the database. Displayed as "דוח מס׳ N".';
